export const DEFAULT_PLACES = [
  'Eraiyur',
  'Palayam',
  'Vadakurumbur',
  'Ellaigaramam',
  'Koovadu',
  'Thenkunam',
  'Adanur',
  'Neivanai',
  'Pilrampattu',
  'Koothanur',
  'Tangal',
  'Mayiladunthangal',
  'Naripalayam',
  'Periykurikkai',
  'A.Athipakkam',
  'Nathamoor',
  'Killiyur',
  'Kunjaram',
  'P.Kunjaram',
  'Ayan Kunjaram',
  'Adaiyur',
  'Dhanam',
  'Seedevi',
  'Poondi',
];

export const DEFAULT_STREETS = [
  'Main road',
  'North street',
  'South street',
  'West street',
  'East street',
  'Mari amman kovil',
  'Aiyanar kovil street',
  'Perumal kovil street',
  'Indra nagar',
];
