export const DEFAULT_PLACES = [
  'Villupuram',
  'Tindivanam',
  'Gingee',
  'Ulundurpet',
  'Vikravandi',
  'Vanur',
  'Marakkanam',
  'Membar',
  'Melmalaiyanur',
  'Kallakurichi',
];

export const DEFAULT_STREETS = [
  'Main Street',
  'Church Street',
  'Market Street',
  'Station Road',
  'Temple Street',
  'School Street',
  'Hospital Road',
  'Bus Stand Road',
  'Railway Colony',
  'New Street',
  'Old Street',
  'Anna Nagar',
  'Gandhi Nagar',
  'Rajaji Street',
  'Periyar Street',
  'Nehru Street',
  'Sivaji Street',
  'Kamarajar Street',
  'Ambedkar Street',
  'Tagore Street',
];
